"""Tamper benchmark: 20 test-weakening pull requests against a sample repo, judged by plain "CI green" and by Knos.

    python scripts/tamper_bench.py [--out docs/TAMPER.md]

"CI green" runs the PR's own CI test steps (the `run:` lines of its .github/workflows/ci.yml) in the PR's tree and
passes on exit 0, as a branch protection rule would. Knos runs knos.jobs.prove.judge(base, pr, cfg), the same function
prove.yml's check job runs. An attack "fools" a judge when the judge passes it although slugify was not fixed.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import re
import shutil
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BENCH = ROOT / "tests" / "bench_tamper"
sys.path.insert(0, str(ROOT / "src"))

from knos.jobs import prove  # noqa: E402


def _attacks():
    spec = importlib.util.spec_from_file_location("tamper_attacks", BENCH / "attacks.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def ci_green(pr: Path) -> bool:
    wf = pr / ".github" / "workflows" / "ci.yml"
    if not wf.is_file():
        return True   # no CI step: nothing fails
    runs = re.findall(r"^\s*-\s*run:\s*(.+)$", wf.read_text(encoding="utf-8"), re.M)
    for cmd in runs:
        cmd = re.sub(r"^python\b", lambda _: f'"{sys.executable}"', cmd.strip())
        env = {**os.environ, "PYTEST_DISABLE_PLUGIN_AUTOLOAD": "1", "PYTHONDONTWRITEBYTECODE": "1"}
        r = subprocess.run(cmd, shell=True, cwd=pr, env=env, capture_output=True, timeout=300)
        if r.returncode != 0:
            return False
    return True


def one(base: Path, tmp: Path, i: int, name: str, fn, cache: dict) -> dict:
    pr = tmp / f"pr{i}"
    shutil.copytree(base, pr)
    fn(pr)
    green = ci_green(pr)
    shutil.rmtree(pr / "__pycache__", ignore_errors=True)
    v = prove.judge(base, pr, {"issue": "1", "test_dirs": ["tests"]}, cache=cache)
    return {"name": name, "ci": green, "knos": v["passed"], "why": "; ".join(v["reasons"]) or "-"}


def run() -> tuple[dict, list[dict]]:
    mod = _attacks()
    with tempfile.TemporaryDirectory(prefix="knos-tamper-") as t:
        tmp = Path(t)
        base = tmp / "base"
        shutil.copytree(BENCH / "sample", base, ignore=shutil.ignore_patterns("__pycache__"))
        jobs = [mod.CONTROL, *mod.ATTACKS]
        cache: dict = {}
        first = one(base, tmp, 0, *jobs[0], cache)   # the control also runs the base side once, for every PR
        with ThreadPoolExecutor(max_workers=8) as ex:
            got = [first, *ex.map(lambda a: one(base, tmp, a[0], *a[1], cache), list(enumerate(jobs))[1:])]
    for g in got:
        g["out_of_scope"] = g["name"] in mod.OUT_OF_SCOPE
    return got[0], got[1:]


def render(control: dict, rows: list[dict]) -> str:
    ci = sum(r["ci"] for r in rows)
    kn = sum(r["knos"] for r in rows)
    yes = lambda b: "PASS (fooled)" if b else "fail"  # noqa: E731
    out = ["# Tamper benchmark", "",
           "Generated by `python scripts/tamper_bench.py`; checked by tests/test_tamper_bench.py.", "",
           "A sample repo (tests/bench_tamper/sample) has issue 1: `slugify` keeps punctuation. The funder's held-out",
           "acceptance tests live in `.knos/acceptance/1/` on the base branch. Each attack below is a pull request that",
           "does NOT fix the bug and instead weakens what judges it (tests/bench_tamper/attacks.py).", "",
           "- **CI green**: run the PR's own CI test steps (its `.github/workflows/ci.yml`) in the PR tree; pass on exit 0.",
           "- **Knos**: `knos.jobs.prove.judge(base, pr, cfg)`, the function prove.yml's `check` job runs: protected",
           "  paths, overlay of the base's tests/config, a random sentinel test and failing canary, fail-to-pass on the",
           "  acceptance tests, pass-to-pass, and test count.", "",
           f"**CI green fooled {ci}/{len(rows)}, Knos fooled {kn}/{len(rows)}.**", "",
           f"Control (the honest fix): CI green {'passes' if control['ci'] else 'fails'}, "
           f"Knos {'passes' if control['knos'] else 'fails'}.", "",
           "| # | attack | CI green | Knos | Knos's reason |", "|---|---|---|---|---|"]
    for i, r in enumerate(rows, 1):
        why = r["why"].replace("|", "\\|")
        if len(why) > 140:
            why = why[:137] + "..."
        out.append(f"| {i} | {r['name']} | {yes(r['ci'])} | {yes(r['knos'])} | {why} |")
    out += ["", "Out of scope: a stub that returns the expected constants for the acceptance inputs passes any judge",
            "that only runs tests it was shown; held-out tests the worker never sees (fixed on chain by the checks",
            "hash) and review are the defence. Code under test also runs inside pytest's process, so a PR that",
            "locates the sentinel names and rewrites the report at exit is not stopped by the check job alone.", ""]
    return "\n".join(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(ROOT / "docs" / "TAMPER.md"))
    a = ap.parse_args(argv)
    control, rows = run()
    text = render(control, rows)
    Path(a.out).write_text(text, encoding="utf-8")
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
